In [1]:
import pandas as pd

In [2]:
account_info = pd.DataFrame({"name": ["Bob", "Mary", "Mita"],"account": [123846, 123972, 347209],"balance": [123, 3972, 7209],})

In [3]:
account_info

   name  account  balance
0   Bob   123846      123
1  Mary   123972     3972
2  Mita   347209     7209

In [4]:
account_info.iloc[1]

name         Mary
account    123972
balance      3972
Name: 1, dtype: object

In [5]:
account_info.iloc[1,2]

3972

In [6]:
account_info.iloc[0:2]

   name  account  balance
0   Bob   123846      123
1  Mary   123972     3972

In [7]:
account_info.iloc[0:2,2]

0     123
1    3972
Name: balance, dtype: int64

In [9]:
import pandas as pd

restaurants = pd.MultiIndex.from_tuples(
    (("Diner", (4, 2)), ("Pandas", (5, 4))),
    names=["restaurant", "location"],
)

inspections = pd.MultiIndex.from_tuples(
    ((0, "score"), (0, "date"), (1, "score"), (1, "date")), names=["inspection", "data"]
)

restaurant_inspections = pd.DataFrame(
    [[90, "02/18", 100, "05/18"], [55, "042/18", 76, "015/18"]],
    index=restaurants,
    columns=inspections,
)

print(restaurant_inspections)

score_columns = restaurant_inspections.columns.get_level_values("data") == "score"

print(score_columns)

inspection              0             1
data                score    date score    date
restaurant location
Diner      (4, 2)      90   02/18   100   05/18
Pandas     (5, 4)      55  042/18    76  015/18
[ True False  True False]

In [10]:
restaurant_inspections

inspection              0             1
data                score    date score    date
restaurant location
Diner      (4, 2)      90   02/18   100   05/18
Pandas     (5, 4)      55  042/18    76  015/18

In [11]:
score_columns

array([ True, False,  True, False])

In [26]:
import pandas as pd

account_info = pd.DataFrame(
    {
        "name": ["Bob", "Mary", "Mita"],
        "account": [123846, 123972, 347209],
        "balance": [123, 3972, 7209],
    }
)
account_info

   name  account  balance
0   Bob   123846      123
1  Mary   123972     3972
2  Mita   347209     7209

In [34]:
account_info.loc[0, "balance"],account_info.iloc[0, 2]

(123, 123)

In [21]:
import numpy as np


customers = pd.MultiIndex.from_tuples(
    (("Bob", "smithb"), ("Mary", "mj100"), ("Mita", "patelm")),
    names=["name", "username"],
)

accounts = pd.MultiIndex.from_tuples(
    ((0, "number"), (0, "balance"), (1, "number"), (1, "balance")), names=["account", "account_info"]
)

account_info = pd.DataFrame(
    [[123846, 123, 123847, 450], [123972, 3972, 123973, 222], [347209, 7209, np.nan, np.nan]],
    index=customers,
    columns=accounts,
)

account_info

account             0                 1
account_info   number balance    number balance
name username
Bob  smithb    123846     123  123847.0   450.0
Mary mj100     123972    3972  123973.0   222.0
Mita patelm    347209    7209       NaN     NaN

In [22]:
account_info.loc[("Mary", "mj100"), pd.IndexSlice[:, "balance"]]

account  account_info
0        balance         3972.0
1        balance          222.0
Name: (Mary, mj100), dtype: float64

In [23]:
import datetime

In [24]:
dti = pd.to_datetime(['1/1/2018', np.datetime64('2018-01-01'),
   ...:                       datetime.datetime(2018, 1, 1)])

In [25]:
dti

DatetimeIndex(['2018-01-01', '2018-01-01', '2018-01-01'], dtype='datetime64[ns]', freq=None)